In [1]:
import numpy as np

class Perceptron:
    def __init__(self, input_size, lr=0.1):
        self.W = np.zeros(input_size + 1)
        self.lr = lr

    def activation_fn(self, x):
        return 1 if x >= 0 else 0

    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a

    def train(self, X, Y, epochs):
        for _ in range(epochs):
            for i in range(Y.shape[0]):
                x = X[i]
                y = self.predict(x)
                e = Y[i] - y
                self.W = self.W + self.lr * e * np.insert(x, 0, 1)

# Define the input data and labels
X = np.array([
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],  # 0
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],  # 1
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],  # 2
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],  # 3
    [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],  # 4
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],  # 5
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],  # 6
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],  # 7
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 1],  # 8
    [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],  # 9
])

Y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

# Create the perceptron and train it
perceptron = Perceptron(input_size=10)
perceptron.train(X, Y, epochs=100)

# Test the perceptron on some input data
test_X = np.array([
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],  # 0
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],  # 1
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],  # 2
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],  # 3
    [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],  # 4
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],  # 5
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],  # 6
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],  # 7
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 1],  # 8
    [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],  # 9
])

for i in range(test_X.shape[0]):
    x = test_X[i]
    y = perceptron.predict(x)
    print(f'{x} is {"even" if y == 0 else "odd"}')


[0 0 0 0 0 0 1 0 0 0] is even
[0 0 0 0 0 0 0 1 0 0] is odd
[0 0 0 0 0 0 0 0 1 0] is even
[0 0 0 0 0 0 0 0 0 1] is odd
[0 0 0 0 0 0 1 1 0 0] is even
[0 0 0 0 0 0 1 0 1 0] is even
[0 0 0 0 0 0 1 1 1 0] is even
[0 0 0 0 0 0 1 1 1 1] is even
[0 0 0 0 0 0 1 0 1 1] is even
[0 0 0 0 0 0 0 1 1 1] is odd


In [ ]:
'''
    Perceptron Class:
        The Perceptron class represents a perceptron model.
        It initializes the perceptron with a weight vector (self.W) of size input_size + 1 (including the bias term) and a learning rate (lr).
        It defines an activation function (activation_fn) that returns 1 if the input is greater than or equal to 0, otherwise 0.
        The predict method predicts the output for a given input by computing the dot product of the input and weight vectors, applying the activation function, and returning the result.
        The train method trains the perceptron using input-output pairs for a specified number of epochs. It iterates over each input-output pair, computes the prediction error, and updates the weights using the perceptron learning rule.

    Input Data:
        The input data (X) consists of binary numbers represented as arrays of length 10.
        The output labels (Y) indicate whether each input number is even (0) or odd (1).

    Training:
        The perceptron is trained using the input data (X) and their corresponding labels (Y) for 100 epochs.

    Testing:
        After training, the perceptron is tested on the same input data to classify whether each number is even or odd.
        For each input number, the prediction is made using the predict method, and the result is printed.
        '''